create database analysis_project
use analysis_project

select * from customer_behaviour_analysis

----------------------------------------------------------------------------
-- Business Insights Questions
----------------------------------------------------------------------------

--1. Which category generates highest revenue?
-- business problem:- company does not know which category contribute most to revenue.

select category,round(sum(purchase_amount),2) as highest_revenue
from customer_behaviour_analysis
group by category
order by highest_revenue desc

--2. Are discounts actually increasing purchase value?
-- Business problem:- Discounts may reduce profit without increasing sales.

select discount_applied,
	   round(sum(purchase_amount),2) as total_amount,
	   avg(purchase_amount) as avg_purchase
from customer_behaviour_analysis
group by discount_applied

--3. what is the total revenue generated by male and female customer?
-- Business problem:- Lack of understanding of revenue contribution by gender segments.

select gender,
	   round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by gender
order by total_revenue desc

--4. Which customer used a discount but still spent more then the average purchase amount?
-- Business problem:- Company cannot identify high spending customers who are also discount users.

select customer_id,
	   round(purchase_amount,2) as purchase_amount,
	   discount_applied
from customer_behaviour_analysis
where discount_applied = 'Yes' and purchase_amount>
			(select avg(purchase_amount) from customer_behaviour_analysis)
order by purchase_amount desc

--5. Which are the top/bottom 5 products with the highest average review rating.
--Business problem:- No visibility into product performance based on customer satisfaction.

-- Top 5 products
select TOP 5 item_purchased,
	   round(avg(purchase_amount),2) as avg_amount
from customer_behaviour_analysis
group by item_purchased
order by avg_amount desc

-- Bottom 5 products
select TOP 5 item_purchased,
	   round(avg(purchase_amount),2) as avg_amount
from customer_behaviour_analysis
group by item_purchased
order by avg_amount 

--6. Average purchase: Standard vs Express
--Business problem: Unclear if faster shipping leads to higher spending.

select shipping_type,
	   round(AVG(purchase_amount),2) as avg_purchase,
	   round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by shipping_type
order by avg_purchase desc

--7. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
--Business problem: The effectiveness of subscription programs is unknown.

select subscription_status,
	   ROUND(avg(purchase_amount),2) as avg_purchase,
	   ROUND(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by subscription_status;

--8. Top 5 products with highest discount usage %
-- Business problem: some products may be overly dependent on discounts

with cte as(
	select item_purchased,
		   COUNT(case when discount_applied = 'Yes' then 1 end) as discount,
		   count(*) as total_no_of_item
	from customer_behaviour_analysis
	group by item_purchased)
select top 5 item_purchased,
	   total_no_of_item,
	   discount,
	   round(discount*100.0/total_no_of_item,2) as discount_percent
from cte
order by discount_percent desc

--9. Segment customer into new, returning and loyal based on their total number of previous purchase and show the count of each segment.
--Business problem: Lack of customer segmentation leads to generic strategies.

select customer_segment,count(customer_segment) as customer_count
from(
	select case when previous_purchases = '0' then 'New customer'
				when previous_purchases between 1 and 15 then 'Returning customer'
				else 'Loyal customer' end as customer_segment
	from customer_behaviour_analysis)t
group by customer_segment;

--10. What are the top 3 most purchased products within each category
--Business problem:- The company doesn't know top performing products within categories.

with cte as (
	select category,
		   item_purchased,
		   count(item_purchased) as most_purchased,
		   DENSE_RANK() over(partition by category order by count(item_purchased) desc) as rnk
	from customer_behaviour_analysis
	group by category,item_purchased)
select * from cte
where rnk<=3

--11. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
--Business problem: Unclear relationship between loyalty and subscription

select customer_type,
	   subscription_status,
	   count(subscription_status) as customer_count
from (
	select case when previous_purchases > 5 then 'Repeat Buyers'
				else 'Normal Buyers' end as customer_type,
		   subscription_status
		   from customer_behaviour_analysis)t
group by customer_type,subscription_status

--12. What is the revenue contribution of each age group?
--Business problem:No visibility into which age group contribution most to revenue

select age_group,round(sum(purchase_amount),2) as total_revenue
from(
	select case when age between 18 and 25 then '18-25'
				when age between 25 and 35 then '25-35'
				when age between 35 and 50 then '35-50'
				else '51+' end as age_group,
				purchase_amount
	from customer_behaviour_analysis)t
group by age_group
order by total_revenue desc







